### PR TITLE
Add autocompletion for functions inside init.sh

### PR DESCRIPTION
**Pull request by bewakes**
The functions inside init.sh will appear as autocompletion options
while issuing command `bro start <project-name> <Tab>.

This will display all the functions defined in `<project-root>/tasks/init.sh`.

### CODE REVIEW

**Comment by ludbek** [comment]
Hey bro!!! thanks for the PR.

Unfortunately `bro` does not support tasks anymore. It only supports `hooks` such as `setup, init and exit`.
The reason for dropping tasks is that, its better to use a bash file and directly invoke it from terminal.
The tasks in `bro` felt like unnecessary abstraction.

But if you wish to have a collection of bash tasks inside a single file, I recommend taking a look at `make`.
Its an awesome tool that can be used for defining tasks with in any project. In fact, I use it instead of `npm run` these days.
I have been using it for tests, deployment, CICD and stuff.

Let me know what you think about the alternatives.

**Comment by bewakes** [comment]
I see. Thanks for the info @ludbek bro. `make` is cool.

I wanted a single command that `cd`s into the project and invokes a command, perhaps invoke make target. More precisely a shortcut to something like : `bro start <project> && make run`. In this particular PR I was trying to achieve something like listing out the possible functions(or say targets within Makefile) which would then be invoked by bro.

I hope that makes sense.

**Comment by ludbek** [comment]
I think I get it now. Previously I felt this PR brings back the tasks from `v3`.
But realised its a cleaver trick that allows us to start a project with different start up behaviours.

Awesome changes. Thanks bro

**Comment by ludbek** [comment]
Btw its not documented but `bro` runs a hook at `tasks/exit[.ext]` when we exit the project with `bro exit`.
Its a good place to stop some services like docker, db, etc.

**Pull request merged**
